# Generated by Django 4.1.7 on 2023-06-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('payment_signature', models.CharField(max_length=100, null=True)),
                ('rec_num', models.CharField(max_length=100, null=True)),
                ('payment_completed', models.IntegerField(default=0)),
                ('paydone', models.DateTimeField(auto_now_add=True)),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.booking')),
            ],
        ),
    ]
