# Generated by Django 4.1.7 on 2023-06-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='rec_num',
        ),
    ]
