# Generated by Django 4.1.7 on 2023-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_remove_paymentstatus_rec_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='payment_completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
