# Generated by Django 4.1.7 on 2023-06-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_alter_paymentstatus_payment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='payment_completed',
        ),
    ]
