# Generated by Django 4.1.7 on 2023-06-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_remove_paymentstatus_customer_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='customer_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.booking'),
        ),
    ]
