# Generated by Django 4.1.7 on 2023-06-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_remove_paymentstatus_movie_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='customer_details',
            new_name='customer_details_id',
        ),
    ]
