# Generated by Django 4.1.7 on 2023-06-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0011_rename_customer_details_id_paymentstatus_customer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='customer_details',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='movieid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
