# Generated by Django 4.1.7 on 2023-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0013_remove_paymentstatus_movieid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
