# Generated by Django 4.1.7 on 2023-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0014_paymentstatus_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
